# Generated by Django 3.2.25 on 2025-11-04 06:20

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('marketing', 'Marketing Agent'), ('allocater', 'Allocater'), ('writer', 'Writer'), ('process_team', 'Process Team'), ('accounts', 'Accounts')], default='marketing', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('topic', models.TextField(blank=True)),
                ('word_count', models.IntegerField()),
                ('referencing_style', models.CharField(blank=True, max_length=100)),
                ('writing_style', models.CharField(blank=True, max_length=100)),
                ('instruction', models.TextField()),
                ('expected_deadline', models.DateTimeField()),
                ('strict_deadline', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_summary', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='job_attachments/')),
                ('status', models.CharField(choices=[('drop', 'Drop'), ('allocated', 'Allocated'), ('query', 'Query'), ('cancel', 'Cancel'), ('hold', 'Hold'), ('process', 'Process'), ('completed', 'Completed')], default='drop', max_length=20)),
                ('status_note', models.TextField(blank=True)),
                ('structure_file', models.FileField(blank=True, null=True, upload_to='writer_uploads/structure/')),
                ('final_copy', models.FileField(blank=True, null=True, upload_to='writer_uploads/final/')),
                ('software_files', models.FileField(blank=True, null=True, upload_to='writer_uploads/software/')),
                ('final_copy_summary', models.TextField(blank=True)),
                ('ai_plag_final_file', models.FileField(blank=True, null=True, upload_to='process_team/ai_plag/final/')),
                ('ai_plag_ai_report', models.FileField(blank=True, null=True, upload_to='process_team/ai_plag/ai_report/')),
                ('ai_plag_plag_report', models.FileField(blank=True, null=True, upload_to='process_team/ai_plag/plag_report/')),
                ('ai_plag_software', models.FileField(blank=True, null=True, upload_to='process_team/ai_plag/software/')),
                ('decoration_final_file', models.FileField(blank=True, null=True, upload_to='process_team/decoration/final/')),
                ('decoration_ai_report', models.FileField(blank=True, null=True, upload_to='process_team/decoration/ai_report/')),
                ('decoration_plag_report', models.FileField(blank=True, null=True, upload_to='process_team/decoration/plag_report/')),
                ('decoration_software', models.FileField(blank=True, null=True, upload_to='process_team/decoration/software/')),
                ('decoration_decorated_file', models.FileField(blank=True, null=True, upload_to='process_team/decoration/decorated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_jobs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
