# Generated by Django 3.2.25 on 2025-11-11 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Time when writer completed work', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='process_team_member',
            field=models.ForeignKey(blank=True, help_text='Process team member assigned to this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_team_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='process_team_status',
            field=models.CharField(choices=[('not_assigned', 'Not Assigned'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], db_index=True, default='not_assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Time when writer started working', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='writer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='allocated_to',
            field=models.ForeignKey(blank=True, help_text='Writer assigned to this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='attachment',
            field=models.FileField(blank=True, help_text='Initial job attachment', null=True, upload_to='job_attachments/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='decoration_decorated_file',
            field=models.FileField(blank=True, help_text='Final decorated/formatted document', null=True, upload_to='process_team/decoration/decorated/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='expected_deadline',
            field=models.DateTimeField(help_text='Expected completion deadline'),
        ),
        migrations.AlterField(
            model_name='job',
            name='final_copy',
            field=models.FileField(blank=True, help_text='Final written document', null=True, upload_to='writer_uploads/final/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='final_copy_summary',
            field=models.TextField(blank=True, help_text='Summary of the final copy'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_summary',
            field=models.TextField(blank=True, help_text='Brief summary of the job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='software_files',
            field=models.FileField(blank=True, help_text='Software-related files (if applicable)', null=True, upload_to='writer_uploads/software/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('drop', 'Drop'), ('allocated', 'Allocated'), ('query', 'Query'), ('cancel', 'Cancel'), ('hold', 'Hold'), ('process', 'Process'), ('completed', 'Completed')], db_index=True, default='drop', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status_note',
            field=models.TextField(blank=True, help_text='Additional notes about current status'),
        ),
        migrations.AlterField(
            model_name='job',
            name='strict_deadline',
            field=models.DateTimeField(help_text='Absolute deadline for job completion'),
        ),
        migrations.AlterField(
            model_name='job',
            name='structure_file',
            field=models.FileField(blank=True, help_text='Structure/outline document', null=True, upload_to='writer_uploads/structure/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='topic',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Job value in currency', max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this user has been approved by an admin.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('marketing_team', 'Marketing Team'), ('allocater', 'Allocater'), ('writer', 'Writer'), ('process_team', 'Process Team'), ('accounts_team', 'Accounts Team')], default='writer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'writer_status'], name='jobs_status_415225_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['allocated_to', 'writer_status'], name='jobs_allocat_68de9f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['process_team_member', 'process_team_status'], name='jobs_process_5de137_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['strict_deadline'], name='jobs_strict__acabd2_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-created_at'], name='jobs_created_91fc39_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_approved'], name='users_role_69ca58_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_notifications', to='authentication.job'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='notificatio_created_8fa075_idx'),
        ),
    ]
